export const mockListings = [
  {
    id: 1,
    title: "1965 Snoopy Metal Lunchbox",
    description: "Classic metal lunchbox with matching thermos, some paint wear on the edges",
    price: 45,
    photoUrl: "https://placehold.co/300x200",
    age: "1960s",
    condition: "Good",
    maker: "Thermos",
    status: "listed",
    sellerId: 3
  },
  {
    id: 2,
    title: "1985 Transformers Lunchbox",
    description: "Plastic dome lid, minor scratches, no thermos included",
    price: 30,
    photoUrl: "https://placehold.co/300x200",
    age: "1980s",
    condition: "Fair",
    maker: "Aladdin",
    status: "listed",
    sellerId: 4
  },
  {
    id: 3,
    title: "1950s Roy Rogers Lunchbox",
    description: "Rare early vinyl lunchbox, excellent condition, no cracks",
    price: 120,
    photoUrl: "https://placehold.co/300x200",
    age: "1950s",
    condition: "Excellent",
    maker: "American Thermos",
    status: "listed",
    sellerId: 3
  },
  {
    id: 4,
    title: "1977 Star Wars Lunchbox",
    description: "Original movie artwork, dome shape, missing thermos cup",
    price: 65,
    photoUrl: "https://placehold.co/300x200",
    age: "1970s",
    condition: "Good",
    maker: "King Seeley",
    status: "listed",
    sellerId: 5
  },
  {
    id: 5,
    title: "1990s Jurassic Park Lunchbox",
    description: "Plastic lunchbox, vibrant colors still intact, includes matching water bottle",
    price: 25,
    photoUrl: "https://placehold.co/300x200",
    age: "1990s",
    condition: "Excellent",
    maker: "Thermos",
    status: "listed",
    sellerId: 6
  },
  {
    id: 6,
    title: "1962 Beatles Lunchbox",
    description: "Highly collectible, some rust on the hinges but graphics are vivid",
    price: 200,
    photoUrl: "https://placehold.co/300x200",
    age: "1960s",
    condition: "Fair",
    maker: "Aladdin",
    status: "listed",
    sellerId: 4
  },
  {
    id: 7,
    title: "1983 He-Man Lunchbox",
    description: "Metal lunchbox with thermos, light surface rust, great display piece",
    price: 55,
    photoUrl: "https://placehold.co/300x200",
    age: "1980s",
    condition: "Good",
    maker: "Aladdin",
    status: "listed",
    sellerId: 5
  },
  {
    id: 8,
    title: "1958 Disneyland Lunchbox",
    description: "Dome-top metal lunchbox featuring early Disneyland artwork",
    price: 150,
    photoUrl: "https://placehold.co/300x200",
    age: "1950s",
    condition: "Good",
    maker: "American Thermos",
    status: "listed",
    sellerId: 3
  },
  {
    id: 9,
    title: "1976 KISS Lunchbox",
    description: "Band artwork lunchbox, some fading on the front panel",
    price: 90,
    photoUrl: "https://placehold.co/300x200",
    age: "1970s",
    condition: "Fair",
    maker: "King Seeley",
    status: "listed",
    sellerId: 6
  },
  {
    id: 10,
    title: "1995 Power Rangers Lunchbox",
    description: "Plastic lunchbox, includes thermos, minor wear on clasp",
    price: 20,
    photoUrl: "https://placehold.co/300x200",
    age: "1990s",
    condition: "Good",
    maker: "Thermos",
    status: "listed",
    sellerId: 5
  },
  {
    id: 11,
    title: "1968 Flintstones Lunchbox",
    description: "Vibrant cartoon artwork, small dent on back panel",
    price: 110,
    photoUrl: "https://placehold.co/300x200",
    age: "1960s",
    condition: "Good",
    maker: "Aladdin",
    status: "listed",
    sellerId: 4
  },
  {
    id: 12,
    title: "1988 Ghostbusters Lunchbox",
    description: "Dome lid lunchbox, complete with thermos, great condition",
    price: 48,
    photoUrl: "https://placehold.co/300x200",
    age: "1980s",
    condition: "Excellent",
    maker: "Aladdin",
    status: "listed",
    sellerId: 6
  },
  {
    id: 13,
    title: "1972 Partridge Family Lunchbox",
    description: "Metal lunchbox, noticeable rust spots but artwork is clear",
    price: 35,
    photoUrl: "https://placehold.co/300x200",
    age: "1970s",
    condition: "Fair",
    maker: "King Seeley",
    status: "listed",
    sellerId: 3
  },
  {
    id: 14,
    title: "1998 Pokemon Lunchbox",
    description: "Plastic lunchbox featuring original 151 artwork, excellent shape",
    price: 40,
    photoUrl: "https://placehold.co/300x200",
    age: "1990s",
    condition: "Excellent",
    maker: "Thermos",
    status: "listed",
    sellerId: 5
  },
  {
    id: 15,
    title: "1954 Howdy Doody Lunchbox",
    description: "One of the earliest licensed character lunchboxes, some wear consistent with age",
    price: 175,
    photoUrl: "https://placehold.co/300x200",
    age: "1950s",
    condition: "Fair",
    maker: "American Thermos",
    status: "listed",
    sellerId: 6
  }
]